# Generated by Django 6.1 on 2026-08-30 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Называние')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('type_games', models.CharField(choices=[('Action', 'Экшен'), ('Adventure', 'Приключения'), ('Puzzle', 'Головоломки')], verbose_name='Тип игры')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('created_at', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'игры',
            },
        ),
        migrations.CreateModel(
            name='GamesReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='MMA')),
                ('text', models.TextField(verbose_name='OueHka')),
                ('raiting', models.IntegerField(choices=[(1, '⭐️'), (2, '⭐️⭐️ '), (3, '⭐️⭐️⭐️'), (4, '⭐️⭐️⭐️⭐️'), (5, '⭐️⭐️⭐️⭐️⭐️')], verbose_name='PenTnHr')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='auto.games')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
    ]
