# Generated by Django 6.1 on 2026-09-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='type_platform',
            field=models.CharField(choices=[('PlayStation 5', 'PS'), ('Xbox Series X', 'Xbox'), ('Computer', 'Pc')], default=1, max_length=50, verbose_name='Платформа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='games',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='type_games',
            field=models.CharField(choices=[('Экшен', 'Action'), ('Приключения', 'Adventure'), ('Головоломки', 'Puzzle')], max_length=50, verbose_name='Тип игры'),
        ),
    ]
