# Generated by Django 6.1 on 2026-09-06 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_games_type_platform_alter_games_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='sezi',
            field=models.FloatField(default=0.0, verbose_name='Размер (ГБ)'),
        ),
        migrations.AlterField(
            model_name='games',
            name='type_platform',
            field=models.CharField(choices=[('PlayStation 5', 'PS'), ('Xbox Series X', 'Xbox'), ('Computer', 'PC')], max_length=50, verbose_name='Платформа'),
        ),
        migrations.CreateModel(
            name='SystemRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(default='Windows 10/11', max_length=100, verbose_name='ОС')),
                ('processor', models.CharField(max_length=150, verbose_name='Процессор')),
                ('ram', models.CharField(max_length=50, verbose_name='Оперативная память')),
                ('graphics', models.CharField(max_length=150, verbose_name='Видеокарта')),
                ('storage', models.CharField(max_length=50, verbose_name='Место на диске')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='auto.games', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Системные требования',
                'verbose_name_plural': 'Системные требования',
            },
        ),
    ]
