# Generated by Django 6.1 on 2026-09-09 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_publisher_games_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='auto.publisher', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='gamesreview',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
    ]
